name: ci
on:
  - push
jobs:
  test-linux-swift-5.2:
    container:
      image: swift:5.2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  test-linux-swift-53:
    container:
      image: swift:5.3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
